resolver: lts-20.17

extra-deps:
- github: lowarn-dsu/lowarn
  commit: f60f7c746e0986ac7d6b2b34092b33fa6e5096db
  subdirs:
  - core
  - runtime
  - cli
  - aeson
- X11-1.10
- xtest-0.2

packages:
- collect-csv
- xmonad-benchmark

ghc-options:
  "$everything": -dynamic-too -rdynamic
