name:                smp-server-benchmark
version:             0.1.0.0
github:              "lowarn-dsu/lowarn-evaluate"
license:             MIT
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Program for benchmarking smp-server
category:            System

description:         Please see the README on GitHub at <https://github.com/lowarn-dsu/lowarn-evaluate/tree/main/smp-server-benchmark#readme>

dependencies:
- async
- base >= 4.7 && < 5
- containers
- process
- simplexmq
- stm
- temporary
- time
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  smp-server-benchmark:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
